__ayetravel__/accounts/urls.py
from django.conf.urls import url
from accounts import views

# TEMPLATE TAGGING
app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name='index'),
    url(r'^index.html', views.ProfileView.as_view()),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^(?P<username>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^recovery/$', views.RecoveryView.as_view(), name='recovery'),
]

__ayetravel__/app/urls.py
from django.conf.urls import url
from app.views import SearchView, IndexView, CalendarView
from django.conf import settings
from django.conf.urls.static import static
from community.views import CommunityTripsList, CommunityTripsDetailed

# TEMPLATE TAGGING
app_name = 'app'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^index.html', IndexView.as_view()),
    url(r'^community/trips/$', CommunityTripsList.as_view(), name='community_list'),
    url(r'^community/trips/(?P<slug>[\w-]+)/$', CommunityTripsDetailed.as_view(), name='community_trips_detailed'),
    url(r'^my/calendar/$', CalendarView.as_view(), name='calendar'),
    url(r'^search/$', SearchView.as_view(), name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

__ayetravel__/ayetravel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app
from app import views

admin.autodiscover()
handler404 = app.views.handler404
handler500 = app.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('app.urls', namespace='app'), name='app'),
    path('accounts/', include('accounts.urls', namespace='accounts'), name='accounts'),
    path('my/trips/', include('trips.urls', namespace='trips'), name='trips'),
    path('community/', include('community.urls', namespace='community'), name='community'),
]

__ayetravel__/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from trips.models import Trips
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures', default='profile_pictures/default.png')
    mfa = models.BooleanField(default=False)
    receive_emails = models.BooleanField(default=True)
    location = models.CharField(max_length=264, blank=True)
    age = models.IntegerField(default=0)
    pins = models.IntegerField(default=0)
    private_account = models.BooleanField(default=False)
    timezone = models.CharField(max_length=5, default='UTC')

    class Meta:
        verbose_name = 'userprofile'
        verbose_name_plural = 'userprofiles'

    def get_profile_picture(self):
        if self.profile_picture:
            return self.profile_picture.url
        else:
            return 'media/profile_pictures/default.png'

    def __str__(self):
        return f'User profile & settings for the user: {self.user_id.get_username()}'


class UserNotifications(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=200, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'notification'
        verbose_name_plural = 'notifications'

    # TODO build out notification system
    def create_notification(self, instance, message):
        UserNotifications.objects.create(user_id=instance, message=message).save()

    def read_notification(self):
        self.read = True
        self.save()

    def delete_notification(self, id_):
        UserNotifications.objects.delete(id=id_).save()

    def __str__(self):
        return str('"' + self.message + '"' + ' for the user: ' + self.user_id.get_username())


# class UserCalendar(models.Model):
#     user_id = models.OneToOneField(User, on_delete=models.CASCADE)
#
#     class Meta:
#         verbose_name = 'usercalendar'
#         verbose_name_plural = 'usercalendars'
#
#     def __str__(self):
#         return f'Calendar data for the user: {self.user_id.get_username()}'
#
#
# @receiver(post_save, sender=User)
# def create_usercalendar(sender, instance, created, **kwargs):
#     if created:
#         UserCalendar.objects.create(user_id=instance)
#
#
# @receiver(post_save, sender=User)
# def save_usercalendar(sender, instance, **kwargs):
#     instance.usercalendar.save()
#
#
# @receiver(post_save, sender=User)
# def delete_usercalendar(sender, instance, **kwargs):
#     instance.usercalendar.delete()


@receiver(post_save, sender=User)
def create_userprofile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user_id=instance, receive_emails=True)


@receiver(post_save, sender=User)
def delete_userprofile(sender, instance, **kwargs):
    instance.userprofile.delete()


@receiver(post_save, sender=User)
def save_userprofile(sender, instance, **kwargs):
    instance.userprofile.save()

__ayetravel__/accounts/forms.py
from django import forms
from django.core import validators


class LoginForm(forms.Form):
    username_textbox = forms.CharField(max_length=25, required=True, label='Username',
                                       widget=forms.TextInput(
                                           attrs={'class': 'form-control',
                                                  'placeholder': 'Enter your username',
                                                  'id': 'username_textbox',
                                                  'type': 'text',
                                                  'name': 'username_textbox',
                                                  }))

    botcatcher = forms.CharField(required=False, validators=[validators.MaxLengthValidator(0)],
                                 widget=forms.HiddenInput(
                                     attrs={'name': 'botcatcher',
                                            'id': 'botcatcher',
                                            }))

    password_textbox = forms.CharField(max_length=60, required=True, label='Password',
                                       widget=forms.PasswordInput(
                                           attrs={'class': 'form-control',
                                                  'placeholder': 'Enter your password',
                                                  'id': 'password_textbox',
                                                  'type': 'password',
                                                  'name': 'password_textbox',
                                                  }))

    remember_me_checkbox = forms.BooleanField(label='', required=False,
                                              widget=forms.CheckboxInput(
                                                 attrs={'class': 'custom-control-input',
                                                        'type': 'checkbox',
                                                        'id': 'checkbox-signin',
                                                        'name': 'remember_me_checkbox'
                                                        }))

__ayetravel__/accounts/views.py
from django.shortcuts import render
from accounts import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import urllib
from urllib.request import urlopen
import json
from django.views.generic import TemplateView, FormView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from app.views import render_user_trips, render_user_notifications


class LoginView(FormView):
    context_object_name = 'login'
    template_name = 'accounts/login.html'
    login_form = forms.LoginForm()

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('app:index'))
        else:
            return render(request, self.template_name, {'form': self.login_form})

    def post(self, request, *args, **kwargs):
        username_form = request.POST.get('username_textbox')
        password_form = request.POST.get('password_textbox')
        remember_me_form = request.POST.get('remember_me_checkbox')
        botcatcher_form = request.POST.get('botcatcher')

        # Begin reCAPTCHA validation
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': '6Lcxam4UAAAAAMJYHMLc6obuBA6R1DHYHHfavqph',
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        # End reCAPTCHA validation

        user = authenticate(username=username_form, password=password_form)

        if result['success'] and botcatcher_form is None:
            if user:
                if user.is_active:
                    # Log the user in
                    login(request, user)
                    # Handle remember me, don't expire user auth if checked
                    if not request.POST.get(remember_me_form, None):
                        # if checked, don't expire
                        request.session.set_expiry(0)
                    # return the redirect of index regardless of remember me checkbox outcome
                    return HttpResponseRedirect(reverse('app:index'))
                else:
                    # Account not active
                    return render(request, self.template_name, {'form': self.login_form,
                                                                'error': 'Account not active.'})
            else:
                # Password incorrect
                return render(request, self.template_name, {'form': self.login_form,
                                                            'error': 'Password incorrect.'})
        else:
            # recaptcha not completed or botcatcher textbox filled out - we have a bot
            return render(request, self.template_name, {'form': self.login_form,
                                                        'error': 'Please complete reCAPTCHA verification.'})


class LogoutView(LoginRequiredMixin, TemplateView):
    context_object_name = 'logout'
    template_name = 'accounts/logout.html'

    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, self.template_name)


class ProfileView(LoginRequiredMixin, DetailView):
    context_object_name = 'profile'
    template_name = 'accounts/profile.html'
    object = User

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_user'] = render_profile(request)
        context['trips'] = render_user_trips(request)
        context['notifs'] = render_user_notifications(request)
        context['trips_total'] = len(render_user_trips(request))
        context['notifs_total'] = len(render_user_notifications(request))
        return render(request, self.template_name, context)


class RecoveryView(LoginRequiredMixin, FormView):
    context_object_name = 'recovery'
    template_name = 'accounts/recovery.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


def render_profile(request):
    current_user = ''
    for user in User.objects.all():
        if request.get_raw_uri().__contains__(user.get_username()):
            current_user = user
            break
    return current_user

__ayetravel__/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>ayetravel - Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="ayetravel" name="Ryan Ciehanski" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static "app/img/favicon.ico" %}">

        <!-- App css -->
        <link href="{% static "app/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "app/css/app.min.css" %}" rel="stylesheet" type="text/css" />
        <script src='https://www.google.com/recaptcha/api.js'></script>
    </head>

    <body class="authentication-bg">
        <div class="account-pages mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card">
                            <!-- Logo -->
                            <div class="card-header pt-4 pb-4 text-center bg-primary">
                                <a href="">
                                    <span><img src="{% static "app/img/logo.png" %}" alt="" height="75"></span>
                                </a>
                            </div>
                            <div class="card-body p-4">
                                <form action="." method="POST">
                                    {% if error %}
                                    <div class="alert alert-danger" role="alert">
                                        <i class="dripicons-wrong mr-2"></i>{{ error }}
                                    </div>
                                    {% endif %}
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="username_textbox">Username</label>
                                        {{ form.username_textbox }}
                                    </div>

                                    <div class="form-group">
                                        <label for="password_textbox">Password</label>
                                        <a href="{% url "accounts:recovery" %}" class="text-muted float-right" tabindex="-1"><small>Forgot your password?</small></a>
                                        {{ form.password_textbox }}
                                    </div>

                                    <div class="form-group mb-3">
                                        <div class="custom-control custom-checkbox">
                                            {{ form.remember_me_checkbox }}
                                            <label class="custom-control-label" for="checkbox-signin">Remember me</label>
                                        </div>
                                    </div>
                                    <center><div class="g-recaptcha" data-sitekey="6Lcxam4UAAAAAOx-9RWDxhalnW1ZIPzoQU5x4M9x"></div></center>
                                    </br>
                                    <div class="form-group mb-0 text-center">
                                        <button class="btn btn-primary" type="submit"> Log In </button>
                                    </div>

                                </form>
                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->
                        <div class="row mt-3">
                            <div class="col-12 text-center">
{#                                <p class="text-muted">Don't have an account? <a href="register.html" class="text-dark ml-1"><b>Sign Up</b></a></p>#}
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->
                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 © ayetravel
        </footer>

        <!-- App js -->
        <script src="{% static "app/js/app.min.js" %}"></script>
    </body>
</html>

__ayetravel__/accounts/templates/accounts/logout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Hyper - Responsive Bootstrap 4 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static "app/assets/../../../static/app/images/favicon.ico" %}">

        <!-- App css -->
        <link href="{% static "app/assets/../../../static/app/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "app/assets/../../../static/app/css/app.min.css" %}" rel="stylesheet" type="text/css" />

    </head>

    <body class="authentication-bg">

        <div class="account-pages mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header pt-4 pb-4 text-center bg-primary">
                                <a href="index.html">
                                    <span><img src="{% static "app/assets/../../../static/app/images/logo.png" %}" alt="" height="18"></span>
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center mt-0 font-weight-bold">See You Again!</h4>
                                    <p class="text-muted mb-4">You are now successfully sign out.</p>
                                </div>

                                <div class="logout-icon m-auto">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                    viewBox="0 0 161.2 161.2" enable-background="new 0 0 161.2 161.2" xml:space="preserve">
                                        <path class="path" fill="none" stroke="#0acf97" stroke-miterlimit="10" d="M425.9,52.1L425.9,52.1c-2.2-2.6-6-2.6-8.3-0.1l-42.7,46.2l-14.3-16.4
                                            c-2.3-2.7-6.2-2.7-8.6-0.1c-1.9,2.1-2,5.6-0.1,7.7l17.6,20.3c0.2,0.3,0.4,0.6,0.6,0.9c1.8,2,4.4,2.5,6.6,1.4c0.7-0.3,1.4-0.8,2-1.5
                                            c0.3-0.3,0.5-0.6,0.7-0.9l46.3-50.1C427.7,57.5,427.7,54.2,425.9,52.1z"/>
                                        <circle class="path" fill="none" stroke="#0acf97" stroke-width="4" stroke-miterlimit="10" cx="80.6" cy="80.6" r="62.1"/>
                                        <polyline class="path" fill="none" stroke="#0acf97" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="113,52.8
                                            74.1,108.4 48.2,86.4 "/>

                                        <circle class="spin" fill="none" stroke="#0acf97" stroke-width="4" stroke-miterlimit="10" stroke-dasharray="12.2175,12.2175" cx="80.6" cy="80.6" r="73.9"/>
                                    </svg>
                                </div> <!-- end logout-icon-->

                            </div> <!-- end card-body-->
                        </div> <!-- end card-->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Back to <a href="{% url "accounts:index" %}" class="text-dark ml-1"><b>Log In</b></a></p>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 ©  ayetravel
        </footer>

        <!-- App js -->
        <script src="{% static "app/assets/../../../static/app/js/app.min.js" %}"></script>
    </body>
</html>

__ayetravel__/accounts/templates/accounts/recovery.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Hyper - Responsive Bootstrap 4 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">

        <!-- App css -->
        <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />

    </head>

    <body class="authentication-bg">

        <div class="account-pages mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card">
                            <!-- Logo -->
                            <div class="card-header pt-4 pb-4 text-center bg-primary">
                                <a href="index.html">
                                    <span><img src="assets/images/logo.png" alt="" height="18"></span>
                                </a>
                            </div>
                            
                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center mt-0 font-weight-bold">Reset Password</h4>
                                    <p class="text-muted mb-4">Enter your email address and we'll send you an email with instructions to reset your password.</p>
                                </div>

                                <form action="#">
                                    <div class="form-group mb-3">
                                        <label for="emailaddress">Email address</label>
                                        <input class="form-control" type="email" id="emailaddress" required="" placeholder="Enter your email">
                                    </div>

                                    <div class="form-group mb-0 text-center">
                                        <button class="btn btn-primary" type="submit">Reset Password</button>
                                    </div>
                                </form>
                            </div> <!-- end card-body-->
                        </div>
                        <!-- end card -->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Back to <a href="pages-login.html" class="text-dark ml-1"><b>Log In</b></a></p>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 © Hyper - Coderthemes.com
        </footer>

        <!-- App js -->
        <script src="assets/js/app.min.js"></script>
    </body>
</html>