__ayetravel__/accounts/urls.py
from django.conf.urls import url
from accounts import views

# TEMPLATE TAGGING
app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name='index'),
    url(r'^index.html', views.ProfileView.as_view()),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^(?P<username>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^recovery/$', views.RecoveryView.as_view(), name='recovery'),
]

__ayetravel__/app/urls.py
from django.conf.urls import url
from app.views import SearchView, IndexView, CalendarView
from django.conf import settings
from django.conf.urls.static import static
from community.views import CommunityTripsList, CommunityTripsDetailed

# TEMPLATE TAGGING
app_name = 'app'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^index.html', IndexView.as_view()),
    url(r'^community/trips/$', CommunityTripsList.as_view(), name='community_list'),
    url(r'^community/trips/(?P<slug>[\w-]+)/$', CommunityTripsDetailed.as_view(), name='community_trips_detailed'),
    url(r'^my/calendar/$', CalendarView.as_view(), name='calendar'),
    url(r'^search/$', SearchView.as_view(), name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

__ayetravel__/ayetravel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app
from app import views

admin.autodiscover()
handler404 = app.views.handler404
handler500 = app.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('app.urls', namespace='app'), name='app'),
    path('accounts/', include('accounts.urls', namespace='accounts'), name='accounts'),
    path('my/trips/', include('trips.urls', namespace='trips'), name='trips'),
    path('community/', include('community.urls', namespace='community'), name='community'),
]

__ayetravel__/trips/urls.py
from django.conf.urls import url
from trips.views import TripsList, TripsDetailed, UpdateTrip, CreateTrip, DeleteTrip
from django.conf import settings
from django.conf.urls.static import static

# TEMPLATE TAGGING
app_name = 'trips'

urlpatterns = [
    url(r'^$', TripsList.as_view(), name='trips_list'),
    url(r'^create/$', CreateTrip.as_view(), name='create_trip'),
    url(r'^(?P<slug>[\w-]+)/$', TripsDetailed.as_view(), name='trips_detailed'),
    url(r'^update/(?P<slug>[\w-]+)/$', UpdateTrip.as_view(), name='update_trip'),
    url(r'^delete/(?P<slug>[\w-]+)/$', DeleteTrip.as_view(), name='delete_trip'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

__ayetravel__/app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
    <html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>{% block title_block %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured travel log and planning service." name="ayetravel" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static "app/img/favicon.ico" %}">

        <!-- third party css -->
        <link href="{% static "app/css/vendor/jquery-jvectormap-1.2.2.css" %}" rel="stylesheet" type="text/css" />
        <!-- third party css end -->

        <!-- App css -->
        <link href="{% static "app/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "app/css/app.min.css" %}" rel="stylesheet" type="text/css" />

    </head>

    <body {% block custom_body %}{% endblock %}>

        <!-- Begin page -->
        <div class="wrapper">

            <!-- ========== Left Sidebar Start ========== -->
            <div class="left-side-menu">

                <div class="slimscroll-menu">

                    <!-- LOGO -->
                    <a href="{% url "app:index" %}" class="logo text-center">
                        <span class="logo-lg">
                            <img src="{% static "app/img/logo.png" %}" alt="" height="75">
                        </span>
                        <span class="logo-sm">
                            <img src="{% static "app/img/logo_sm.png" %}" alt="" height="25">
                        </span>
                    </a>

                    <!--- Sidemenu -->
                    <ul class="metismenu side-nav">

                        <li class="side-nav-title side-nav-item">Navigation</li>

                        <li class="side-nav-item">
                            <a href="{% url "app:index" %}" class="side-nav-link">
                                <i class="dripicons-meter"></i>
                                <span> Dashboard </span>
                                <span class="menu-arrow"></span>
                            </a>
                        </li>

                        <li class="side-nav-item">
                            <a href="{% url "trips:trips_list" %}" class="side-nav-link">
                                <i class="dripicons-location"></i>
                                <span> Trips </span>
                                <span class="menu-arrow"></span>
                            </a>
                        </li>

                        <li class="side-nav-item">
                            <a href="{% url "app:calendar" %}" class="side-nav-link">
                                <i class="dripicons-calendar"></i>
                                <span> Calendar </span>
                                <span class="menu-arrow"></span>
                            </a>
                        </li>

                        <li class="side-nav-item">
                            <a href="{% url "app:community_list" %}" class="side-nav-link">
                                <i class="dripicons-list"></i>
                                <span> Community </span>
                                <span class="menu-arrow"></span>
                            </a>
                        </li>

                    </ul>

                    <!-- Help Box -->
                    <div class="help-box text-white text-center">
                        <a href="javascript: void(0);" class="float-right close-btn text-white">
                            <i class="mdi mdi-close"></i>
                        </a>
                        <img src="{% static "app/img/help-icon.svg" %}" height="90" alt="Helper Icon Image" />
                        <h5 class="mt-3">Give Back</h5>
                        <p class="mb-3">Inspire others by sharing your trip card with the community.</p>
                        <a href="javascript: void(0);" class="btn btn-outline-light btn-sm">Share</a>
                    </div>
                    <!-- end Help Box -->
                    <!-- End Sidebar -->

                    <div class="clearfix"></div>

                </div>
                <!-- Sidebar -left -->

            </div>
            <!-- Left Sidebar End -->

            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">

                    <!-- Topbar Start -->
                    <div class="navbar-custom">
                        <ul class="list-unstyled topbar-right-menu float-right mb-0">
                            <li class="dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <i class="dripicons-bell noti-icon"></i>
                                    {% if notifs_total > 0 %}
                                        <span class="noti-icon-badge"></span>
                                    {% endif %}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg">

                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <h5 class="m-0">
                                            <span class="float-right">
                                                <a href="javascript: void(0);" class="text-dark">
                                                    {% if notifs_total > 0 %}
                                                    <small>Clear All</small>
                                                    {% endif %}
                                                </a>
                                            </span>Notifications for {{ user.get_username }}
                                        </h5>
                                    </div>

                                    <div class="slimscroll" style="max-height: 230px;">

                                    {% if notifs_total > 0 %}
                                    {% for notif in notifs %}
                                        <!-- item-->
                                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                                            <div class="notify-icon bg-primary">
                                                <i class="mdi mdi-comment-account-outline"></i>
                                            </div>
                                            <p class="notify-details">{{ notif.message }}
                                                <small class="text-muted">{{ notif.timestamp }}</small>
                                            </p>
                                        </a>
                                    {% endfor %}
                                    {% else %}
                                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            No notifications :(
                                        </div>
                                    {% endif %}

                                    </div>

                                    <!-- All-->
                                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                                        View All
                                    </a>

                                </div>
                            </li>

                            <li class="dropdown notification-list">
                                <a class="nav-link dropdown-toggle nav-user arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <span class="account-user-avatar">
                                        <img src="{{ user.userprofile.get_profile_picture }}" alt="" class="rounded-circle">
                                    </span>
                                    <span>
                                        <span class="account-user-name">{{ user.get_short_name }}</span>
                                        <span class="account-position">{{ user.get_username }}</span>
                                    </span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown ">
                                    <!-- item-->
                                    <div class=" dropdown-header noti-title">
                                        <h6 class="text-overflow m-0">Welcome!</h6>
                                    </div>

                                    <!-- item-->
                                    <a href="{% url "accounts:profile" user.get_username %}" class="dropdown-item notify-item">
                                        <i class="mdi mdi-account-circle"></i>
                                        <span>My Profile</span>
                                    </a>

                                    <!-- item-->
                                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                                        <i class="mdi mdi-account-settings-variant"></i>
                                        <span>Settings</span>
                                    </a>

                                    <!-- item-->
                                    <a href="{% url "accounts:logout" %}" class="dropdown-item notify-item">
                                        <i class="mdi mdi-logout"></i>
                                        <span>Logout</span>
                                    </a>

                                </div>
                            </li>

                        </ul>
                        <button class="button-menu-mobile open-left disable-btn">
                            <i class="mdi mdi-menu"></i>
                        </button>
                        <div class="app-search">
                            <form method="get" action="{% url "app:search" %}">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input name="search" type="text" class="form-control" placeholder="Search by trip name...">
                                    <span class="mdi mdi-magnify"></span>
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- end Topbar -->

                    <!-- Start Content-->
                    <div class="container-fluid">

                        {% block body_block %}{% endblock %}

                    </div>

                        <!-- Footer Start -->
                        <footer class="footer">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-6">
                                        2018 © ayetravel
                                    </div>
                                    <div class="col-md-6">
                                        <div class="text-md-right footer-links d-none d-md-block">
                                            <a href="javascript: void(0);">About</a>
                                            <a href="javascript: void(0);">Support</a>
                                            <a href="javascript: void(0);">Contact Us</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </footer>
                        <!-- end Footer -->

                    </div>
                </div>
            <!-- ============================================================== -->
            <!-- End Page content -->
            <!-- ============================================================== -->

        </div>
        <!-- END wrapper -->

        <!-- bundle -->
        <script src="{% static "app/js/app.min.js" %}"></script>

        <!-- third party js -->
        <script src="{% static "app/js/vendor/Chart.bundle.min.js" %}"></script>
        <script src="{% static "app/js/vendor/jquery-jvectormap-1.2.2.min.js" %}"></script>
        <script src="{% static "app/js/vendor/jquery-jvectormap-world-mill-en.js" %}"></script>
        <!-- third party js ends -->

        {% block scipts_block %}{% endblock %}

        <!-- demo app -->
        <script src="{% static "app/js/pages/demo.dashboard.js" %}"></script>
        <!-- end demo js-->
    </body>

</html>

__ayetravel__/app/templates/app/base_error.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>ayetravel - 500</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static "app/img/favicon.ico" %}">

        <!-- App css -->
        <link href="{% static "app/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "app/css/app.min.css" %}" rel="stylesheet" type="text/css" />

    </head>

    <body class="authentication-bg">

        <div class="account-pages mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card">
                            <!-- Logo -->
                            <div class="card-header pt-4 pb-4 text-center bg-primary">
                                <a href="{% url "app:index" %}">
                                    <span><img src="{% static "app/img/logo.png" %}" alt="" height="18"></span>
                                </a>
                            </div>

                            <div class="card-body p-4">

                                <div class="text-center">
                                    {% block body_block %}
                                    {% endblock %}
                                </div>

                            </div> <!-- end card-body-->
                        </div>
                        <!-- end card-->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 © ayetravel
        </footer>

        <!-- App js -->
        <script src="{% static "app/js/app.min.js" %}"></script>
    </body>
</html>

__ayetravel__/app/templates/app/calendar.html
<!DOCTYPE html>
{% extends "app/base.html" %}
{% load static %}

{% block title_block %}
    ayetravel - My Calendar
{% endblock %}

{% block body_block %}
                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url "app:index" %}">Dashboard</a></li>
                                            <li class="breadcrumb-item active">Calendar</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Calendar</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <div class="row">
                            <div class="col-12">

                                <div class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <a href="#" data-toggle="modal" data-target="#add-category" class="btn btn-lg font-16 btn-primary btn-block  ">
                                                    <i class="mdi mdi-plus-circle-outline"></i> Create New Event
                                                </a>
                                                <div id="external-events" class="m-t-20">
                                                    <br>
                                                    <p class="text-muted">Drag and drop your event or click in the calendar</p>
                                                    <div class="external-event bg-success" data-class="bg-success">
                                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>New Theme Release
                                                    </div>
                                                    <div class="external-event bg-info" data-class="bg-info">
                                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>My Event
                                                    </div>
                                                    <div class="external-event bg-warning" data-class="bg-warning">
                                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>Meet manager
                                                    </div>
                                                    <div class="external-event bg-danger" data-class="bg-danger">
                                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>Create New theme
                                                    </div>
                                                </div>
    
                                                <!-- checkbox -->
                                                <div class="custom-control custom-checkbox mt-3">
                                                    <input type="checkbox" class="custom-control-input" id="drop-remove">
                                                    <label class="custom-control-label" for="drop-remove">Remove after drop</label>
                                                </div>
    
                                                <div class="mt-5 d-none d-xl-block">
                                                    <h5 class="text-center">How It Works ?</h5>
    
                                                    <ul class="pl-3">
                                                        <li class="text-muted mb-3">
                                                            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                                                        </li>
                                                        <li class="text-muted mb-3">
                                                            Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.
                                                        </li>
                                                        <li class="text-muted mb-3">
                                                            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div> <!-- end col-->

                                            <div class="col-lg-9">
                                                <div id="calendar"></div>
                                            </div> <!-- end col -->

                                        </div>  <!-- end row -->
                                    </div> <!-- end card body-->
                                </div> <!-- end card -->

                                <!-- Add New Event MODAL -->
                                <div class="modal fade" id="event-modal" tabindex="-1">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header pr-4 pl-4 border-bottom-0 d-block">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                <h4 class="modal-title">Add New Event</h4>
                                            </div>
                                            <div class="modal-body pt-3 pr-4 pl-4">
                                            </div>
                                            <div class="text-right pb-4 pr-4">
                                                <button type="button" class="btn btn-light " data-dismiss="modal">Close</button>
                                                <button type="button" class="btn btn-success save-event  ">Create event</button>
                                                <button type="button" class="btn btn-danger delete-event  " data-dismiss="modal">Delete</button>
                                            </div>
                                        </div> <!-- end modal-content-->
                                    </div> <!-- end modal dialog-->
                                </div>
                                <!-- end modal-->

                                <!-- Modal Add Category -->
                                <div class="modal fade" id="add-category" tabindex="-1">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header border-bottom-0 d-block">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                <h4 class="modal-title">Add a category</h4>
                                            </div>
                                            <div class="modal-body p-4">
                                                <form>
                                                    <div class="form-group">
                                                        <label class="control-label">Category Name</label>
                                                        <input class="form-control form-white" placeholder="Enter name" type="text" name="category-name"/>
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="control-label">Choose Category Color</label>
                                                        <select class="form-control form-white" data-placeholder="Choose a color..." name="category-color">
                                                            <option value="primary">Primary</option>
                                                            <option value="success">Success</option>
                                                            <option value="danger">Danger</option>
                                                            <option value="info">Info</option>
                                                            <option value="warning">Warning</option>
                                                            <option value="dark">Dark</option>
                                                        </select>
                                                    </div>

                                                </form>

                                                <div class="text-right">
                                                    <button type="button" class="btn btn-light " data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary ml-1   save-category" data-dismiss="modal">Save</button>
                                                </div>

                                            </div> <!-- end modal-body-->
                                        </div> <!-- end modal-content-->
                                    </div> <!-- end modal dialog-->
                                </div>
                                <!-- end modal-->
                            </div>
                            <!-- end col-12 -->
                        </div> <!-- end row -->
                        
                    </div> <!-- container -->

{% endblock %}