__ayetravel__/app/urls.py
from django.conf.urls import url
from app.views import SearchView, IndexView, CalendarView
from django.conf import settings
from django.conf.urls.static import static
from community.views import CommunityTripsList, CommunityTripsDetailed

# TEMPLATE TAGGING
app_name = 'app'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^index.html', IndexView.as_view()),
    url(r'^community/trips/$', CommunityTripsList.as_view(), name='community_list'),
    url(r'^community/trips/(?P<slug>[\w-]+)/$', CommunityTripsDetailed.as_view(), name='community_trips_detailed'),
    url(r'^my/calendar/$', CalendarView.as_view(), name='calendar'),
    url(r'^search/$', SearchView.as_view(), name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

__ayetravel__/ayetravel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app
from app import views

admin.autodiscover()
handler404 = app.views.handler404
handler500 = app.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('app.urls', namespace='app'), name='app'),
    path('accounts/', include('accounts.urls', namespace='accounts'), name='accounts'),
    path('my/trips/', include('trips.urls', namespace='trips'), name='trips'),
    path('community/', include('community.urls', namespace='community'), name='community'),
]

__ayetravel__/trips/urls.py
from django.conf.urls import url
from trips.views import TripsList, TripsDetailed, UpdateTrip, CreateTrip, DeleteTrip
from django.conf import settings
from django.conf.urls.static import static

# TEMPLATE TAGGING
app_name = 'trips'

urlpatterns = [
    url(r'^$', TripsList.as_view(), name='trips_list'),
    url(r'^create/$', CreateTrip.as_view(), name='create_trip'),
    url(r'^(?P<slug>[\w-]+)/$', TripsDetailed.as_view(), name='trips_detailed'),
    url(r'^update/(?P<slug>[\w-]+)/$', UpdateTrip.as_view(), name='update_trip'),
    url(r'^delete/(?P<slug>[\w-]+)/$', DeleteTrip.as_view(), name='delete_trip'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

__ayetravel__/trips/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from ayetravel.utils import unique_slug_generator
from django.db.models.signals import pre_save


class Trips(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True, default='', blank=True)
    name = models.CharField(max_length=50, blank=True)
    user_location = models.CharField(max_length=100, blank=True)
    destination = models.CharField(max_length=100, blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    budget = models.IntegerField(default=0)
    participants_total = models.IntegerField(default=1)
    comments_total = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='trips/trip_pictures', blank=True, null=True)
    public = models.BooleanField(default=False)
    pins_total = models.IntegerField(default=0)
    packing_list = models.TextField(blank=True, max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    files = models.FileField(upload_to='trips/trip_files', null=True, blank=True)

    class Meta:
        verbose_name = 'trip'
        verbose_name_plural = 'trips'
        # TODO research trip permissions
        # permissions = (
        #     ("view_trip", "Can view this specific trip."),
        #     ("modify_trip", "Can modify this specific trip."),
        #     ("delete_trip", "Can remove this specific trip."))

    def __str__(self):
        return str(f'Trip ID: ' + str(self.pk) + ' "' + self.name + '"' + ' created by '
                   + str(self.user_id.get_username()))

    def get_absolute_url(self):
        return reverse('app:trips_detailed', kwargs={'slug': self.slug})


class Comments(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return str(f'Comment ID: ' + str(self.pk) + ' "' + self.message + '"' + ' created by '
                   + str(self.user_id.get_username()) + ' left on Trip ID: ' + self.trip.pk)


class Pins(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'pin'
        verbose_name_plural = 'pins'

    def __str__(self):
        return str(f'Pin ID: ' + str(self.pk) + ' for trip: '
                   + '"' + self.trip.name + '"' + 'left by user: ' + self.user_id.get_username())


class Participants(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'participant'
        verbose_name_plural = 'participants_total'

    def __str__(self):
        return str(f'Participant: ' + self.user_id.get_username() + " for trip: " + self.trip.pk)


def pre_save_receiver(sender, instance, *args, **kwargs):
    if instance.slug == '':
        instance.slug = unique_slug_generator(instance)


pre_save.connect(pre_save_receiver, sender=Trips)

__ayetravel__/trips/forms.py
from django import forms
from trips.models import Trips


class CreateTripForm(forms.ModelForm):
    name = forms.CharField(max_length=50)
    user_location = forms.CharField(max_length=100)
    destination = forms.CharField(max_length=100)
    start_date = forms.DateField()
    end_date = forms.DateField()
    budget = forms.IntegerField()
    participants = forms.IntegerField()
    picture = forms.ImageField()

    class Meta:
        model = Trips
        fields = '__all__'

__ayetravel__/trips/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from trips.models import Trips
from app.views import render_user_trips, render_community_trips, render_user_notifications


class TripsDetailed(LoginRequiredMixin, DetailView):
    context_object_name = 'trips_detailed'
    template_name = 'trips/trips_detailed.html'
    object = Trips

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['community_trips'] = render_community_trips(request)
        context['trips'] = self.clean_object(request)
        context['notifs'] = render_user_notifications(request)
        context['trips_total'] = len(render_user_trips(request))
        context['notifs_total'] = len(render_user_notifications(request))
        return render(request, self.template_name, context)

    def get_object(self, queryset=Trips):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Trips, slug=slug_)

    def clean_object(self, request):
        slug_ = self.kwargs.get('slug')
        obj = self.get_object()
        if obj.user_id.get_username() == request.user.get_username() or obj.public:
            return get_object_or_404(Trips, slug=slug_)
        else:
            return render(request, 'app/500.html', {'error': 'This is a private trip which you '
                                                             'do not have permissions to view.'})


class CreateTrip(LoginRequiredMixin, CreateView):
    context_object_name = 'create_trip'
    template_name = 'trips/create_trip.html'
    object = Trips
    model = Trips
    fields = '__all__'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notifs'] = render_user_notifications(request)
        context['notifs_total'] = len(render_user_notifications(request))
        return render(request, self.template_name, context)

    def get_object(self, queryset=Trips):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Trips, slug=slug_)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UpdateTrip(LoginRequiredMixin, UpdateView):
    context_object_name = 'update_trip'
    template_name = 'trips/create_trip.html'
    model = Trips
    fields = '__all__'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trips'] = self.get_object()
        context['notifs'] = render_user_notifications(request)
        context['notifs_total'] = len(render_user_notifications(request))
        return render(request, self.template_name, context)

    def get_object(self, queryset=Trips):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Trips, slug=slug_)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class DeleteTrip(LoginRequiredMixin, DeleteView):
    context_object_name = 'update_trip'
    template_name = 'trips/create_trip.html'
    model = Trips
    success_url = reverse_lazy('app:trips_list')

    def get_object(self, queryset=Trips):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Trips, slug=slug_)

    def post(self, request, *args, **kwargs):
        pass


class TripsList(LoginRequiredMixin, ListView):
    context_object_name = 'trips_list'
    template_name = 'trips/trips_list.html'
    object_list = Trips.objects.all()

    def get(self, request, *args, **kwargs):
        self.object_list = render_user_trips(request)
        context = super().get_context_data(**kwargs)
        context['trips'] = render_user_trips(request)
        context['notifs'] = render_user_notifications(request)
        context['trips_total'] = len(render_user_trips(request))
        context['notifs_total'] = len(render_user_notifications(request))
        return render(request, self.template_name, context)

__ayetravel__/trips/templates/trips/create_trip.html
<!DOCTYPE html>
{% extends "app/base.html" %}
{% load static %}

{% block scripts_block %}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
{% endblock %}

{% block title_block %}
    ayetravel - Create Trip
{% endblock %}

{% block custom_body %}onload="initialize()"{% endblock %}

{% block body_block %}
        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{% url "app:index" %}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{% url "trips:trips_list" %}">Trips</a></li>
                                <li class="breadcrumb-item active">Create Trip</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Create Trip</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->


            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Basic Info</h4>

                            <div class="row">
                                <div class="col-md-6">
                                    <p class="mb-1 mt-3 font-weight-bold text-muted">Name</p>
                                    <p class="text-muted font-14">
                                        Name your trip something fun!
                                    </p>

                                    <input type="text" class="form-control" data-toggle="input-mask">
                                    <span class="font-13 text-muted">e.g "Fucking Reno!"</span>

                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <p class="mb-1 mt-3 font-weight-bold text-muted">Budget</p>
                                    <p class="text-muted font-14">
                                        How much are you looking to spend on this trip?
                                    </p>

                                    <input type="text" class="form-control" data-toggle="input-mask">
                                    <span class="font-13 text-muted">e.g $3,800</span>

                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <p class="mb-1 mt-3 font-weight-bold text-muted">Where are you currently?</p>
                                    <p class="text-muted font-14">
                                        Your address or city will work.
                                    </p>
                                    <script>
                                        var autocomplete;
                                        function initialize() {
                                          autocomplete = new google.maps.places.Autocomplete(
                                              /** @type {HTMLInputElement} */(document.getElementById('autocomplete')),
                                              { types: ['geocode'] });
                                          google.maps.event.addListener(autocomplete, 'place_changed', function() {
                                          });
                                        }
                                    </script>
                                    <input type="text" class="form-control" onFocus="geolocate()" data-toggle="input-mask">
                                    <span class="font-13 text-muted">e.g "Chicago, IL"</span>
                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <p class="mb-1 mt-3 font-weight-bold text-muted">Where are you going?</p>
                                    <p class="text-muted font-14">
                                        Hopefully somewhere warm!
                                    </p>
                                    <script>
                                        var autocomplete;
                                        function initialize() {
                                          autocomplete = new google.maps.places.Autocomplete(
                                              /** @type {HTMLInputElement} */(document.getElementById('autocomplete')),
                                              { types: ['geocode'] });
                                          google.maps.event.addListener(autocomplete, 'place_changed', function() {
                                          });
                                        }
                                    </script>
                                    <input type="text" class="form-control" onFocus="geolocate()" data-toggle="input-mask">
                                    <span class="font-13 text-muted">e.g "San Fransisco, CA"</span>
                                </div> <!-- end col -->

                            </div> <!-- end row -->

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>
            <!-- end row-->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">When are you planing this trip?</h4>
                            <p class="text-muted font-14">
                                (Don't worry you can change this later)
                            </p>

                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group mb-3">
                                        <label>Start Date</label>
                                        <input type="text" class="form-control date" id="singledaterange" data-toggle="date-picker" data-cancel-class="btn-warning">
                                        <span class="font-13 text-muted">e.g "DD/MM/YYYY"</span>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group mb-3">
                                        <label>End Date</label>
                                        <input type="text" class="form-control date" id="singledaterange" data-toggle="date-picker" data-cancel-class="btn-warning">
                                        <span class="font-13 text-muted">e.g "DD/MM/YYYY"</span>
                                    </div>
                                </div>
                            </div>
                          </div>
                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            <!-- end row -->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group mb-0">
                                <label>Packing List</label>
                                <p class="text-muted font-13">
                                    List all the things you'll need for this job.
                                </p>
                                <textarea data-toggle="maxlength" class="form-control" maxlength="1000" rows="9"
                                    placeholder="Shampoo, soap, condoms, wine..."></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Community Trip</h4>
                            <p class="text-muted font-14 mb-3">
                                Would you like to make your trip public to the community?
                            </p>
                            <!-- Success Switch-->
                            <input type="checkbox" id="switch3" checked data-switch="success"/>
                            <label for="switch3" data-off-label="No" data-on-label="Yes"></label>
                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div> <!-- container -->

{% endblock %}

__ayetravel__/trips/templates/trips/trips_list.html
<!DOCTYPE html>
{% extends "app/base.html" %}
{% load static %}

{% block title_block %}
    ayetravel - My Trips
{% endblock %}

{% block body_block %}
                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url "app:index" %}">Dashboard</a></li>
                                            <li class="breadcrumb-item active">Trips</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Trips</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <div class="row mb-2">
                            <div class="col-sm-4">
                                <a href="{% url "trips:create_trip" %}">
                                    <button type="submit" class="btn btn-danger btn-rounded mb-3"><i class="mdi mdi-plus"></i> Create Trip</button>
                                </a>
                            </div>
                            <div class="col-sm-8">
                                <div class="text-sm-right">
                                    <div class="btn-group mb-3">
                                        <button type="button" class="btn btn-primary">All</button>
                                    </div>
                                    <div class="btn-group mb-3 ml-1">
                                        <button type="button" class="btn btn-light">Ongoing</button>
                                        <button type="button" class="btn btn-light">Finished</button>
                                    </div>
                                    <div class="btn-group mb-3 ml-2 d-none d-sm-inline-block">
                                        <button type="button" class="btn btn-dark"><i class="dripicons-view-apps"></i></button>
                                    </div>
                                    <div class="btn-group mb-3 d-none d-sm-inline-block">
                                        <button type="button" class="btn btn-link text-dark"><i class="dripicons-checklist"></i></button>
                                    </div>
                                </div>
                            </div><!-- end col-->
                        </div> 
                        <!-- end row-->

                        <div class="row">
                            {% for trip in trips %}
                            <div class="col-md-6 col-xl-3">
                                <!-- project card -->
                                <div class="card d-block">
                                    <div class="card-body">
                                        <div class="dropdown card-widgets">
                                            <a href="{{ trip.slug }}" class="dropdown-toggle arrow-none" data-toggle="dropdown" aria-expanded="false">
                                                <i class="dripicons-dots-3"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <!-- item-->
                                                <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-pencil mr-1"></i>Edit</a>
                                                <!-- item-->
                                                <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-delete mr-1"></i>Delete</a>
                                                <!-- item-->
                                                <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-email-outline mr-1"></i>Invite</a>
                                                <!-- item-->
                                                <a href="javascript:void(0);" class="dropdown-item"><i class="mdi mdi-exit-to-app mr-1"></i>Leave</a>
                                            </div>
                                        </div>
                                        <!-- project title-->
                                        <h4 class="mt-0">
                                            <a href="{{ trip.slug }}" class="text-dark">{{ trip.name }}</a>
                                        </h4>
                                        <div class="badge badge-success mb-3">Finished</div>

                                        <p class="text-muted font-13 mb-3">
                                            From: {{ trip.user_location }} <br>
                                            Destination: {{ trip.destination }} <br>
                                            Budget: {{ trip.budget }} <br>
                                            Participants: {{ trip.participants_total }}
                                        </p>

                                        <!-- project detail-->
                                        <p class="mb-1">
                                            <span class="pr-2 text-nowrap mb-2 d-inline-block">
                                                <i class="mdi mdi-format-list-bulleted-type text-muted"></i>
                                                <b>{{ trip.pins_total }}</b> Pins
                                            </span>
                                            <span class="text-nowrap mb-2 d-inline-block">
                                                <i class="mdi mdi-comment-multiple-outline text-muted"></i>
                                                <b>{{ trip.comments_total }}</b> Comments
                                            </span>
                                        </p>
                                        <div>
                                            <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ trip.user_id.get_username }}" class="d-inline-block">
                                                <img src="{{ trip.user_id.userprofile.get_profile_picture }}" class="rounded-circle avatar-xs" alt="">
                                            </a>
    
                                            <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="" data-original-title="Michael Zenaty" class="d-inline-block">
                                                <img src="{% static "app/img/users/avatar-7.jpg" %}" class="rounded-circle avatar-xs" alt="friend">
                                            </a>

                                            <a href="javascript:void(0);" class="d-inline-block text-dark font-weight-bold ml-2">
                                                +7 more
                                            </a>
                                        </div>
                                    </div> <!-- end card-body-->
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item p-3">
                                            <!-- project progress-->
                                            <p class="mb-2 font-weight-bold">Progress <span class="float-right">100%</span></p>
                                            <div class="progress progress-sm">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                                </div><!-- /.progress-bar -->
                                            </div><!-- /.progress -->
                                        </li>
                                    </ul>
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                            {% endfor %}
                        </div>
                        <!-- end row-->
                        
                    </div> <!-- container -->


{% endblock %}